language: python
dist: focal
python:
  - 3.8
  - 3.9
cache:
  pip: true
  directories:
    - '$HOME/.cache/pre-commit'
    - '$HOME/.cache/pypoetry'

env:
  global:
    - secure: 'uMvvcZ/Av5KkbgPt4xmZWoR07KueIKeL2DRyDwYAzqV3LqDVcUi3CAAcy7DylLw3u/iIvRVROV38E94fmaoVKFolSZk9hrgwEFw/IuVKWX2swJlMBdQ7aVkkxta/bdAvKJ97OtpCgCK3/T02WWPGofAqjzfqailwxHwOKLbr4lhU21q+UGq1KtfI1eMAixK6U/sy3ldnlcml1Y9ELdY4KpHV1nOF/K7VIK4ltd5u2RBAGWc375QXgYfg2uNCroJlImexV3ckdu18W+Iw9mBmyAblYWxMtfT+VSTzQX1FTFbeiPTBj0rwyGqTktgtJ0D+j5k3cJkCTbSEtY2ME87WRICuVaegdDXwGKfVHNLHyz63M/LriHpjB7wNT0vMV60njPZQYDbotM3X/+IY48B+MFVhQc5DcepyrFwc1MnhxOkdn706SlDT/2rI6j2fCF3opWsFq3y/EPCxX8IltQMhWNyffXohpJ2XNItGmKuYk7ScavdeBrZc1KN0OD64GtRLD7idls2clRoYC8TIhXhr9D5+0bIlpX7YHtWM1ex/qBQchup0JJSnooxK1h5aEndQNSPOqw4xbYtahdFb0AFhL5mHchvJewxRXke7NkFWvSWa++KWDqziEyzazI9YHs2F9UXrCimzqRvrdpccCFiAwDwCIzoTglHNTrCrGVq0VgE='

before_install:
  - pip install poetry pre-commit

install:
  - poetry install

script:
  - poetry run invoke test

before_deploy:
  - poetry config pypi-token.pypi $PYPI_PASSWORD

deploy:
  - provider: script
    skip_existing: true
    script: poetry publish --build
    on:
      branch: main
      tags: true
      condition: '$TRAVIS_PYTHON_VERSION == 3.8'
